### ISSUE TITLE
have you seen `oquat`?

### ISSUE THREAD

**Issue by cthoyt** [Ostrzyciel/ontology-quality-2022#1]
Hey, this repository is really cool! I found it because you're using the Bioregistry

I actually did something complementary in https://github.com/cthoyt/oquat - are you still working on this repo?

**Comment by Ostrzyciel** [comment]
Hi! No, I haven't seen that, but it looks very interesting. It's kind of similar to the OBO Dashboard, but with more granularity and calls to action... that's actually very nice :)

I'm not actively working on this repo at the moment, but I have published a paper on this ([full version](https://ebooks.iospress.nl/volumearticle/60841), [preprint](https://arxiv.org/abs/2205.02892)). The paper kind of suggests that tools like yours are what's needed for maintaining constantly high ontology quality.

Feel free to reuse code from here (with attribution of course :) ), I can also try to answer any questions you might have.

**Comment by cthoyt** [comment]
Very cool! I will share this paper with the OBO Community. Several of us are trying to more systematically (with massive manual effort :p) address the inconsistencies across OBO foundry
